### ISSUE TITLE
Must be able to handle chunks with no data

### ISSUE THREAD

**Issue by tft-kyrre** [TromsFylkestrafikk/ragnarok-sink#16]
Find a solution for how to handle chunks with no data (e.g. Skyttel 2024-03-17).
ChunkArchive won't create an empty archive, which makes sense, so a possible workaround would be to add a dummy file, but we better find a more elegant solution.
Returning **null** from the fetch() function should be allowed, but this currently leads to an exception in SinkHandler.php.
See [https://github.com/TromsFylkestrafikk/ragnarok-skyttel/issues/8](https://github.com/TromsFylkestrafikk/ragnarok-skyttel/issues/8)

**Comment by tfk-kaare** [comment]
This issue belongs to the ragnarok repository. The API call for fetch allows null in return, as it should be. The solution must lie within the ragnarok logics.

**Comment by tfk-kaare** [comment]
Issue moved.
